/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_use = 3,
  anon_sym_scenario = 4,
  anon_sym_seed = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_time = 8,
  anon_sym_duration = 9,
  anon_sym_total = 10,
  anon_sym_stream = 11,
  anon_sym_COLON = 12,
  anon_sym_EQ = 13,
  sym_quoted_identifier = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_inject = 18,
  anon_sym_for = 19,
  anon_sym_on = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  anon_sym_SEMI = 23,
  anon_sym_hit = 24,
  anon_sym_near_miss = 25,
  anon_sym_non_hit = 26,
  anon_sym_faults = 27,
  anon_sym_oracle = 28,
  sym_rate = 29,
  sym_percent = 30,
  sym_duration = 31,
  sym_number = 32,
  sym_string = 33,
  anon_sym_true = 34,
  anon_sym_false = 35,
  sym_source_file = 36,
  sym_use_declaration = 37,
  sym_scenario_declaration = 38,
  sym_time_clause = 39,
  sym_total_clause = 40,
  sym_stream_block = 41,
  sym_field_override = 42,
  sym_field_name = 43,
  sym_gen_expr = 44,
  sym_gen_func = 45,
  sym__gen_arg = 46,
  sym_named_arg = 47,
  sym_literal = 48,
  sym_inject_block = 49,
  sym_stream_list = 50,
  sym_inject_line = 51,
  sym_mode_keyword = 52,
  sym_param_assign = 53,
  sym_faults_block = 54,
  sym_fault_line = 55,
  sym_oracle_block = 56,
  sym_boolean = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_scenario_declaration_repeat1 = 59,
  aux_sym_scenario_declaration_repeat2 = 60,
  aux_sym_stream_block_repeat1 = 61,
  aux_sym_gen_func_repeat1 = 62,
  aux_sym_inject_block_repeat1 = 63,
  aux_sym_stream_list_repeat1 = 64,
  aux_sym_inject_line_repeat1 = 65,
  aux_sym_faults_block_repeat1 = 66,
  aux_sym_oracle_block_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [anon_sym_scenario] = "scenario",
  [anon_sym_seed] = "seed",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_time] = "time",
  [anon_sym_duration] = "duration",
  [anon_sym_total] = "total",
  [anon_sym_stream] = "stream",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [sym_quoted_identifier] = "quoted_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_inject] = "inject",
  [anon_sym_for] = "for",
  [anon_sym_on] = "on",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [anon_sym_hit] = "hit",
  [anon_sym_near_miss] = "near_miss",
  [anon_sym_non_hit] = "non_hit",
  [anon_sym_faults] = "faults",
  [anon_sym_oracle] = "oracle",
  [sym_rate] = "rate",
  [sym_percent] = "percent",
  [sym_duration] = "duration",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_use_declaration] = "use_declaration",
  [sym_scenario_declaration] = "scenario_declaration",
  [sym_time_clause] = "time_clause",
  [sym_total_clause] = "total_clause",
  [sym_stream_block] = "stream_block",
  [sym_field_override] = "field_override",
  [sym_field_name] = "field_name",
  [sym_gen_expr] = "gen_expr",
  [sym_gen_func] = "gen_func",
  [sym__gen_arg] = "_gen_arg",
  [sym_named_arg] = "named_arg",
  [sym_literal] = "literal",
  [sym_inject_block] = "inject_block",
  [sym_stream_list] = "stream_list",
  [sym_inject_line] = "inject_line",
  [sym_mode_keyword] = "mode_keyword",
  [sym_param_assign] = "param_assign",
  [sym_faults_block] = "faults_block",
  [sym_fault_line] = "fault_line",
  [sym_oracle_block] = "oracle_block",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_scenario_declaration_repeat1] = "scenario_declaration_repeat1",
  [aux_sym_scenario_declaration_repeat2] = "scenario_declaration_repeat2",
  [aux_sym_stream_block_repeat1] = "stream_block_repeat1",
  [aux_sym_gen_func_repeat1] = "gen_func_repeat1",
  [aux_sym_inject_block_repeat1] = "inject_block_repeat1",
  [aux_sym_stream_list_repeat1] = "stream_list_repeat1",
  [aux_sym_inject_line_repeat1] = "inject_line_repeat1",
  [aux_sym_faults_block_repeat1] = "faults_block_repeat1",
  [aux_sym_oracle_block_repeat1] = "oracle_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_scenario] = anon_sym_scenario,
  [anon_sym_seed] = anon_sym_seed,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_duration] = anon_sym_duration,
  [anon_sym_total] = anon_sym_total,
  [anon_sym_stream] = anon_sym_stream,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_inject] = anon_sym_inject,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_hit] = anon_sym_hit,
  [anon_sym_near_miss] = anon_sym_near_miss,
  [anon_sym_non_hit] = anon_sym_non_hit,
  [anon_sym_faults] = anon_sym_faults,
  [anon_sym_oracle] = anon_sym_oracle,
  [sym_rate] = sym_rate,
  [sym_percent] = sym_percent,
  [sym_duration] = sym_duration,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_use_declaration] = sym_use_declaration,
  [sym_scenario_declaration] = sym_scenario_declaration,
  [sym_time_clause] = sym_time_clause,
  [sym_total_clause] = sym_total_clause,
  [sym_stream_block] = sym_stream_block,
  [sym_field_override] = sym_field_override,
  [sym_field_name] = sym_field_name,
  [sym_gen_expr] = sym_gen_expr,
  [sym_gen_func] = sym_gen_func,
  [sym__gen_arg] = sym__gen_arg,
  [sym_named_arg] = sym_named_arg,
  [sym_literal] = sym_literal,
  [sym_inject_block] = sym_inject_block,
  [sym_stream_list] = sym_stream_list,
  [sym_inject_line] = sym_inject_line,
  [sym_mode_keyword] = sym_mode_keyword,
  [sym_param_assign] = sym_param_assign,
  [sym_faults_block] = sym_faults_block,
  [sym_fault_line] = sym_fault_line,
  [sym_oracle_block] = sym_oracle_block,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_scenario_declaration_repeat1] = aux_sym_scenario_declaration_repeat1,
  [aux_sym_scenario_declaration_repeat2] = aux_sym_scenario_declaration_repeat2,
  [aux_sym_stream_block_repeat1] = aux_sym_stream_block_repeat1,
  [aux_sym_gen_func_repeat1] = aux_sym_gen_func_repeat1,
  [aux_sym_inject_block_repeat1] = aux_sym_inject_block_repeat1,
  [aux_sym_stream_list_repeat1] = aux_sym_stream_list_repeat1,
  [aux_sym_inject_line_repeat1] = aux_sym_inject_line_repeat1,
  [aux_sym_faults_block_repeat1] = aux_sym_faults_block_repeat1,
  [aux_sym_oracle_block_repeat1] = aux_sym_oracle_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_duration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_total] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stream] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inject] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_near_miss] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_non_hit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_faults] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_oracle] = {
    .visible = true,
    .named = false,
  },
  [sym_rate] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_time_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_total_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_stream_block] = {
    .visible = true,
    .named = true,
  },
  [sym_field_override] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_gen_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_gen_func] = {
    .visible = true,
    .named = true,
  },
  [sym__gen_arg] = {
    .visible = false,
    .named = true,
  },
  [sym_named_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_inject_block] = {
    .visible = true,
    .named = true,
  },
  [sym_stream_list] = {
    .visible = true,
    .named = true,
  },
  [sym_inject_line] = {
    .visible = true,
    .named = true,
  },
  [sym_mode_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_param_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_faults_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fault_line] = {
    .visible = true,
    .named = true,
  },
  [sym_oracle_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stream_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_gen_func_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inject_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stream_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inject_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_faults_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_oracle_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_count = 2,
  field_dur = 3,
  field_function = 4,
  field_key = 5,
  field_mode = 6,
  field_name = 7,
  field_percent = 8,
  field_rate = 9,
  field_rule = 10,
  field_seed = 11,
  field_start = 12,
  field_value = 13,
  field_window = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_count] = "count",
  [field_dur] = "dur",
  [field_function] = "function",
  [field_key] = "key",
  [field_mode] = "mode",
  [field_name] = "name",
  [field_percent] = "percent",
  [field_rate] = "rate",
  [field_rule] = "rule",
  [field_seed] = "seed",
  [field_start] = "start",
  [field_value] = "value",
  [field_window] = "window",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 1},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_count, 1},
  [1] =
    {field_name, 1},
    {field_seed, 3},
  [3] =
    {field_dur, 3},
    {field_start, 1},
  [5] =
    {field_alias, 1},
    {field_rate, 4},
    {field_window, 3},
  [8] =
    {field_name, 0},
    {field_percent, 1},
  [10] =
    {field_key, 0},
    {field_value, 2},
  [12] =
    {field_rule, 2},
  [13] =
    {field_name, 0},
    {field_value, 2},
  [15] =
    {field_mode, 0},
    {field_percent, 1},
  [17] =
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 3,
        '(', 22,
        ')', 24,
        ',', 23,
        '/', 7,
        ':', 19,
        ';', 27,
        '=', 20,
        '[', 25,
        ']', 26,
        '`', 14,
        '{', 17,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '/') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '/') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '`') ADVANCE(21);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(28);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(8);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_quoted_identifier);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_rate);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_percent);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(29);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'd', 1,
        'f', 2,
        'h', 3,
        'i', 4,
        'n', 5,
        'o', 6,
        's', 7,
        't', 8,
        'u', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(27);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'j') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_hit);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 33:
      if (lookahead == '_') ADVANCE(47);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 46:
      if (lookahead == '_') ADVANCE(59);
      END_STATE();
    case 47:
      if (lookahead == 'h') ADVANCE(60);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 49:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_seed);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_time);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 59:
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_total);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_faults);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_inject);
      END_STATE();
    case 68:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_oracle);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_stream);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_non_hit);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_duration);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_scenario);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_near_miss);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_scenario] = ACTIONS(1),
    [anon_sym_seed] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_duration] = ACTIONS(1),
    [anon_sym_total] = ACTIONS(1),
    [anon_sym_stream] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_quoted_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_inject] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_hit] = ACTIONS(1),
    [anon_sym_near_miss] = ACTIONS(1),
    [anon_sym_non_hit] = ACTIONS(1),
    [anon_sym_faults] = ACTIONS(1),
    [anon_sym_oracle] = ACTIONS(1),
    [sym_percent] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym_use_declaration] = STATE(17),
    [sym_scenario_declaration] = STATE(111),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_scenario] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_stream,
    ACTIONS(13), 1,
      anon_sym_inject,
    ACTIONS(15), 1,
      anon_sym_faults,
    ACTIONS(17), 1,
      anon_sym_oracle,
    STATE(46), 1,
      sym_faults_block,
    STATE(75), 1,
      sym_oracle_block,
    STATE(3), 2,
      sym_stream_block,
      aux_sym_scenario_declaration_repeat1,
    STATE(6), 2,
      sym_inject_block,
      aux_sym_scenario_declaration_repeat2,
  [33] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_stream,
    ACTIONS(13), 1,
      anon_sym_inject,
    ACTIONS(15), 1,
      anon_sym_faults,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_faults_block,
    STATE(90), 1,
      sym_oracle_block,
    STATE(5), 2,
      sym_inject_block,
      aux_sym_scenario_declaration_repeat2,
    STATE(7), 2,
      sym_stream_block,
      aux_sym_scenario_declaration_repeat1,
  [66] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(38), 1,
      sym_gen_expr,
    STATE(47), 1,
      sym_boolean,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 2,
      sym_gen_func,
      sym_literal,
  [91] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_inject,
    ACTIONS(15), 1,
      anon_sym_faults,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_faults_block,
    STATE(110), 1,
      sym_oracle_block,
    STATE(12), 2,
      sym_inject_block,
      aux_sym_scenario_declaration_repeat2,
  [117] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_inject,
    ACTIONS(15), 1,
      anon_sym_faults,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_faults_block,
    STATE(90), 1,
      sym_oracle_block,
    STATE(12), 2,
      sym_inject_block,
      aux_sym_scenario_declaration_repeat2,
  [143] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_stream,
    STATE(7), 2,
      sym_stream_block,
      aux_sym_scenario_declaration_repeat1,
    ACTIONS(29), 4,
      anon_sym_RBRACE,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [160] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_mode_keyword,
    STATE(9), 2,
      sym_inject_line,
      aux_sym_inject_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_non_hit,
  [179] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_mode_keyword,
    STATE(9), 2,
      sym_inject_line,
      aux_sym_inject_block_repeat1,
    ACTIONS(40), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_non_hit,
  [198] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    ACTIONS(47), 2,
      sym_number,
      sym_string,
    STATE(35), 2,
      sym__gen_arg,
      sym_named_arg,
  [216] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_field_name,
    ACTIONS(49), 2,
      sym_quoted_identifier,
      sym_identifier,
    STATE(11), 2,
      sym_field_override,
      aux_sym_stream_block_repeat1,
  [234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_inject,
    STATE(12), 2,
      sym_inject_block,
      aux_sym_scenario_declaration_repeat2,
    ACTIONS(54), 3,
      anon_sym_RBRACE,
      anon_sym_faults,
      anon_sym_oracle,
  [250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 5,
      anon_sym_RBRACE,
      anon_sym_stream,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [264] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_field_name,
    ACTIONS(63), 2,
      sym_quoted_identifier,
      sym_identifier,
    STATE(16), 2,
      sym_field_override,
      aux_sym_stream_block_repeat1,
  [282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(65), 1,
      sym_mode_keyword,
    STATE(8), 2,
      sym_inject_line,
      aux_sym_inject_block_repeat1,
    ACTIONS(36), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_non_hit,
  [298] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_field_name,
    ACTIONS(63), 2,
      sym_quoted_identifier,
      sym_identifier,
    STATE(11), 2,
      sym_field_override,
      aux_sym_stream_block_repeat1,
  [316] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_scenario,
    STATE(81), 1,
      sym_scenario_declaration,
    STATE(23), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
  [333] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(69), 2,
      sym_number,
      sym_string,
    STATE(64), 2,
      sym__gen_arg,
      sym_named_arg,
  [348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 5,
      anon_sym_RBRACE,
      anon_sym_stream,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 5,
      anon_sym_RBRACE,
      anon_sym_stream,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 5,
      anon_sym_RBRACE,
      anon_sym_stream,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [381] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    STATE(27), 2,
      sym_fault_line,
      aux_sym_faults_block_repeat1,
  [395] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_use,
    ACTIONS(84), 1,
      anon_sym_scenario,
    STATE(23), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
  [409] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_oracle_block_repeat1,
    STATE(105), 1,
      sym_param_assign,
  [425] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_oracle_block_repeat1,
    STATE(105), 1,
      sym_param_assign,
  [441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(22), 2,
      sym_fault_line,
      aux_sym_faults_block_repeat1,
  [455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(27), 2,
      sym_fault_line,
      aux_sym_faults_block_repeat1,
  [469] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_SEMI,
    STATE(32), 2,
      sym_param_assign,
      aux_sym_inject_line_repeat1,
  [483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 4,
      anon_sym_RBRACE,
      anon_sym_inject,
      anon_sym_faults,
      anon_sym_oracle,
  [493] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_oracle_block_repeat1,
    STATE(105), 1,
      sym_param_assign,
  [509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      anon_sym_RBRACE,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_non_hit,
  [519] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(110), 1,
      anon_sym_SEMI,
    STATE(34), 2,
      sym_param_assign,
      aux_sym_inject_line_repeat1,
  [533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 4,
      anon_sym_RBRACE,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_non_hit,
  [543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_SEMI,
    STATE(34), 2,
      sym_param_assign,
      aux_sym_inject_line_repeat1,
  [557] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_gen_func_repeat1,
  [570] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_number,
    ACTIONS(123), 2,
      sym_duration,
      sym_string,
  [581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_stream_list_repeat1,
  [621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(104), 1,
      sym_oracle_block,
  [634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(110), 1,
      sym_oracle_block,
  [647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_stream_list_repeat1,
  [660] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_stream_list_repeat1,
  [673] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_oracle,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      sym_oracle_block,
  [695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [713] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_gen_func_repeat1,
  [726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [735] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_gen_func_repeat1,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_use,
      anon_sym_scenario,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    STATE(85), 1,
      sym_stream_list,
  [766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_RBRACE,
      anon_sym_oracle,
  [774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [790] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_SEMI,
      sym_identifier,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_time,
    STATE(60), 1,
      sym_time_clause,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_total,
    STATE(2), 1,
      sym_total_clause,
  [826] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_RBRACE,
      anon_sym_oracle,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      sym_number,
      sym_string,
  [842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_percent,
  [865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_duration,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_string,
  [879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_for,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
  [914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_EQ,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_EQ,
  [928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
  [935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
  [942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LBRACE,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_seed,
  [956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_percent,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_rate,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_total,
  [984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COLON,
  [991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_identifier,
  [998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_LBRACE,
  [1005] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
  [1012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [1019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_number,
  [1026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [1033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
  [1040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_LBRACE,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_LPAREN,
  [1061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_string,
  [1068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [1075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_on,
  [1089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
  [1096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_percent,
  [1103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_duration,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_COLON,
  [1124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
  [1131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
  [1138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_SEMI,
  [1145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_number,
  [1152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_identifier,
  [1166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_identifier,
  [1173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [1180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
  [1187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 117,
  [SMALL_STATE(7)] = 143,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 179,
  [SMALL_STATE(10)] = 198,
  [SMALL_STATE(11)] = 216,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 250,
  [SMALL_STATE(14)] = 264,
  [SMALL_STATE(15)] = 282,
  [SMALL_STATE(16)] = 298,
  [SMALL_STATE(17)] = 316,
  [SMALL_STATE(18)] = 333,
  [SMALL_STATE(19)] = 348,
  [SMALL_STATE(20)] = 359,
  [SMALL_STATE(21)] = 370,
  [SMALL_STATE(22)] = 381,
  [SMALL_STATE(23)] = 395,
  [SMALL_STATE(24)] = 409,
  [SMALL_STATE(25)] = 425,
  [SMALL_STATE(26)] = 441,
  [SMALL_STATE(27)] = 455,
  [SMALL_STATE(28)] = 469,
  [SMALL_STATE(29)] = 483,
  [SMALL_STATE(30)] = 493,
  [SMALL_STATE(31)] = 509,
  [SMALL_STATE(32)] = 519,
  [SMALL_STATE(33)] = 533,
  [SMALL_STATE(34)] = 543,
  [SMALL_STATE(35)] = 557,
  [SMALL_STATE(36)] = 570,
  [SMALL_STATE(37)] = 581,
  [SMALL_STATE(38)] = 590,
  [SMALL_STATE(39)] = 599,
  [SMALL_STATE(40)] = 608,
  [SMALL_STATE(41)] = 621,
  [SMALL_STATE(42)] = 634,
  [SMALL_STATE(43)] = 647,
  [SMALL_STATE(44)] = 660,
  [SMALL_STATE(45)] = 673,
  [SMALL_STATE(46)] = 682,
  [SMALL_STATE(47)] = 695,
  [SMALL_STATE(48)] = 704,
  [SMALL_STATE(49)] = 713,
  [SMALL_STATE(50)] = 726,
  [SMALL_STATE(51)] = 735,
  [SMALL_STATE(52)] = 748,
  [SMALL_STATE(53)] = 756,
  [SMALL_STATE(54)] = 766,
  [SMALL_STATE(55)] = 774,
  [SMALL_STATE(56)] = 782,
  [SMALL_STATE(57)] = 790,
  [SMALL_STATE(58)] = 798,
  [SMALL_STATE(59)] = 806,
  [SMALL_STATE(60)] = 816,
  [SMALL_STATE(61)] = 826,
  [SMALL_STATE(62)] = 834,
  [SMALL_STATE(63)] = 842,
  [SMALL_STATE(64)] = 850,
  [SMALL_STATE(65)] = 858,
  [SMALL_STATE(66)] = 865,
  [SMALL_STATE(67)] = 872,
  [SMALL_STATE(68)] = 879,
  [SMALL_STATE(69)] = 886,
  [SMALL_STATE(70)] = 893,
  [SMALL_STATE(71)] = 900,
  [SMALL_STATE(72)] = 907,
  [SMALL_STATE(73)] = 914,
  [SMALL_STATE(74)] = 921,
  [SMALL_STATE(75)] = 928,
  [SMALL_STATE(76)] = 935,
  [SMALL_STATE(77)] = 942,
  [SMALL_STATE(78)] = 949,
  [SMALL_STATE(79)] = 956,
  [SMALL_STATE(80)] = 963,
  [SMALL_STATE(81)] = 970,
  [SMALL_STATE(82)] = 977,
  [SMALL_STATE(83)] = 984,
  [SMALL_STATE(84)] = 991,
  [SMALL_STATE(85)] = 998,
  [SMALL_STATE(86)] = 1005,
  [SMALL_STATE(87)] = 1012,
  [SMALL_STATE(88)] = 1019,
  [SMALL_STATE(89)] = 1026,
  [SMALL_STATE(90)] = 1033,
  [SMALL_STATE(91)] = 1040,
  [SMALL_STATE(92)] = 1047,
  [SMALL_STATE(93)] = 1054,
  [SMALL_STATE(94)] = 1061,
  [SMALL_STATE(95)] = 1068,
  [SMALL_STATE(96)] = 1075,
  [SMALL_STATE(97)] = 1082,
  [SMALL_STATE(98)] = 1089,
  [SMALL_STATE(99)] = 1096,
  [SMALL_STATE(100)] = 1103,
  [SMALL_STATE(101)] = 1110,
  [SMALL_STATE(102)] = 1117,
  [SMALL_STATE(103)] = 1124,
  [SMALL_STATE(104)] = 1131,
  [SMALL_STATE(105)] = 1138,
  [SMALL_STATE(106)] = 1145,
  [SMALL_STATE(107)] = 1152,
  [SMALL_STATE(108)] = 1159,
  [SMALL_STATE(109)] = 1166,
  [SMALL_STATE(110)] = 1173,
  [SMALL_STATE(111)] = 1180,
  [SMALL_STATE(112)] = 1187,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_declaration_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inject_block_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inject_block_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stream_block_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stream_block_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_declaration_repeat2, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(69),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_block, 5, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_total_clause, 2, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_block, 7, 0, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_block, 8, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_oracle_block_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_oracle_block_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_faults_block_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_faults_block_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inject_block, 8, 0, 7),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inject_line, 3, 0, 9),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inject_line, 4, 0, 9),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inject_line_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inject_line_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_override, 3, 0, 8),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gen_expr, 1, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stream_list_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stream_list_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gen_func, 3, 0, 10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gen_func, 4, 0, 10),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gen_func, 5, 0, 10),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_gen_func_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_gen_func_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_faults_block, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fault_line, 3, 0, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_assign, 3, 0, 6),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_faults_block, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_arg, 3, 0, 6),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 12, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_list, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_keyword, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_clause, 4, 0, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_list, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 9, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oracle_block, 4, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 8, 0, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 11, 0, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oracle_block, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 10, 0, 2),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wfg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
